author: Dr. Lefteris Kokoris-Kogias
description: 'Lefteris Kokoris-Kogias is a Research Scientist at Novi and an Assistant Professor at IST Austria leading the SPiDerS group.'
username: lefkok
highlighter: rouge